CREATE TABLE BESCHIKKING (
    BESCHIKKING_ID INTEGER PRIMARY KEY,
        CLIENT_ID INTEGER,
        CODE VARCHAR(20),
        COMMENTAAR VARCHAR(200),
        DATUMAFGIFTE DATE,
        GRONDSLAGEN INTEGER,
        HEEFT_VOORZIENINGEN_BESCHIKTE_VOORZIENING_ID INTEGER,
        TOEWIJZING_TOEWIJZING_ID INTEGER,
        WET_ENUM_ID INTEGER
);

CREATE TABLE BESCHIKTE_VOORZIENING (
    BESCHIKTE_VOORZIENING_ID INTEGER PRIMARY KEY,
        CODE VARCHAR(20),
        DATUMEINDE DATE,
        DATUMEINDEOORSPRONKELIJK DATE,
        DATUMSTART DATE,
        EENHEID_ENUM_ID INTEGER,
        FREQUENTIE_ENUM_ID INTEGER,
        HEEFT_LEVERINGSVORM_293_ID INTEGER,
        IS_VOORZIENING_VOORZIENING_ID INTEGER,
        LEVERINGSVORM_287_ENUM_ID INTEGER,
        OMVANG INTEGER,
        REDENEINDE DATE,
        STATUS VARCHAR(50),
        TOEGEWEZEN_PRODUCT_TOEWIJZING_ID INTEGER,
        WET_ENUM_ID INTEGER
);

CREATE TABLE CLIENT (
    RECHTSPERSOON_ID INTEGER PRIMARY KEY,
        CODE VARCHAR(80),
        GEZAGSDRAGERGEKEND_ENUM_ID INTEGER,
        JURIDISCHESTATUS VARCHAR(80),
        WETTELIJKEVERTEGENWOORDIGING VARCHAR(80)
);

CREATE TABLE DECLARATIEREGEL (
    DECLARATIEREGEL_ID INTEGER PRIMARY KEY,
        BEDRAG DECIMAL(10,2),
        BETREFT_CLIENT_ID INTEGER,
        CODE VARCHAR(20),
        DATUMEINDE DATE,
        DATUMSTART DATE,
        IS_VOOR_BESCHIKKING_ID INTEGER,
        VALT_BINNEN_DECLARATIE_ID INTEGER
);

CREATE TABLE MEDEWERKER (
    MEDEWERKER_ID INTEGER PRIMARY KEY,
        ACHTERNAAM VARCHAR(200),
        DATUMINDIENST DATE,
        DATUMUITDIENST DATE,
        EMAILADRES VARCHAR(255),
        EXTERN_ENUM_ID INTEGER,
        FUNCTIE VARCHAR(50),
        GESLACHTSAANDUIDING VARCHAR(255),
        MEDEWERKERIDENTIFICATIE VARCHAR(255),
        MEDEWERKERTOELICHTING VARCHAR(255),
        ROEPNAAM VARCHAR(255),
        TELEFOONNUMMER VARCHAR(20),
        VOORLETTERS VARCHAR(20),
        VOORVOEGSELACHTERNAAM VARCHAR(255)
);

CREATE TABLE WET_ENUM (
    WET_ENUM_ID INTEGER PRIMARY KEY,
    VALUE VARCHAR(255)
);

INSERT INTO WET_ENUM (WET_ENUM_ID, VALUE) VALUES
    (1, 'ANDERE_WET'),
    (2, 'BIJZONDERE_BIJSTAND'),
    (3, 'I_O_A_W_I_O_A_Z_'),
    (4, 'JEUGDWET'),
    (5, 'LEEG'),
    (6, 'NIET_VAN_TOEPASSING'),
    (7, 'ONBEKEND'),
    (8, 'PARTICIPATIEWET_PW_I'),
    (9, 'WMO');

-- ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_GEN_INGESCHREVENPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES INGESCHREVENPERSOON (RECHTSPERSOON_ID);
-- -- Generalization to INGESCHREVENPERSOON

-- ALTER TABLE CLIENTBEGELEIDER ADD CONSTRAINT FK_CLIENTBEGELEIDER_GEN_MEDEWERKER FOREIGN KEY (MEDEWERKER_ID) REFERENCES MEDEWERKER (MEDEWERKER_ID);
-- -- Generalization to MEDEWERKER

-- ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- Generalization to RECHTSPERSOON

-- ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_GEN_RECHTSPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- Generalization to RECHTSPERSOON

-- ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_GEN_NATUURLIJKPERSOON FOREIGN KEY (RECHTSPERSOON_ID) REFERENCES NATUURLIJKPERSOON (RECHTSPERSOON_ID);
-- -- Generalization to NATUURLIJKPERSOON

-- ALTER TABLE KP_CLNTBGLDR_CLNT ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_1 FOREIGN KEY (CLIENTBEGELEIDER_ID) REFERENCES CLIENTBEGELEIDER (MEDEWERKER_ID);
-- -- CLIENTBEGELEIDER (many-to-many junction, Connector_ID: 941)

-- ALTER TABLE KP_CLNTBGLDR_CLNT ADD CONSTRAINT FK_KP_CLNTBGLDR_CLNT_2 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (RECHTSPERSOON_ID);
-- -- CLIENT (many-to-many junction, Connector_ID: 941)

-- ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_BOVENLIGGEND FOREIGN KEY (BOVENLIGGEND_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- -- BOVENLIGGEND (0..* to 0..1, Connector_ID: 405)

-- ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_HEEFT FOREIGN KEY (HEEFT_CONTRACT_ID) REFERENCES CONTRACT (CONTRACT_ID);
-- -- HEEFT (1 to 0..*, Connector_ID: 926)

-- ALTER TABLE VOORZIENING ADD CONSTRAINT FK_VOORZIENING_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_VOORZIENINGSOORT_ID) REFERENCES VOORZIENINGSOORT (VOORZIENINGSOORT_ID);
-- -- VALT_BINNEN (0..* to 1, Connector_ID: 1031)

-- ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_BETREFT FOREIGN KEY (BETREFT_CLIENT_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- BETREFT (0..* to 1, Connector_ID: 1032)

-- ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_LEVERANCIER FOREIGN KEY (LEVERANCIER_LEVERANCIER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- LEVERANCIER (0..* to 1, Connector_ID: 1033)

-- ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_BETREFT_2 FOREIGN KEY (BETREFT_VOORZIENING_ID) REFERENCES VOORZIENING (VOORZIENING_ID);
-- -- BETREFT (0..* to 1, Connector_ID: 1034)

-- ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_LEVERT_VOORZIENING FOREIGN KEY (LEVERT_VOORZIENING_LEVERANCIER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- LEVERT_VOORZIENING (0..* to 0..1, Connector_ID: 1038)

-- ALTER TABLE VOORZIENING ADD CONSTRAINT FK_VOORZIENING_HEEFT FOREIGN KEY (HEEFT_TARIEF_ID) REFERENCES TARIEF (TARIEF_ID);
-- -- HEEFT (1 to 1..*, Connector_ID: 1040)

-- ALTER TABLE CONTRACT ADD CONSTRAINT FK_CONTRACT_BEVAT FOREIGN KEY (BEVAT_TARIEF_ID) REFERENCES TARIEF (TARIEF_ID);
-- -- BEVAT (1 to 0..*, Connector_ID: 1041)

-- ALTER TABLE TARIEF ADD CONSTRAINT FK_TARIEF_HEEFT FOREIGN KEY (HEEFT_LEVERANCIER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- HEEFT (0..* to 1, Connector_ID: 1042)

-- ALTER TABLE LEVERANCIER ADD CONSTRAINT FK_LEVERANCIER_LEVERDE_PRESTATIE FOREIGN KEY (LEVERDE_PRESTATIE_LEVERING_ID) REFERENCES LEVERING (LEVERING_ID);
-- -- LEVERDE_PRESTATIE (1 to 0..*, Connector_ID: 1046)

-- ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_VOORZIENING FOREIGN KEY (VOORZIENING_VOORZIENING_ID) REFERENCES VOORZIENING (VOORZIENING_ID);
-- -- VOORZIENING (0..* to 1, Connector_ID: 1047)

-- ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_GELEVERDE_ZORG FOREIGN KEY (GELEVERDE_ZORG_TOEWIJZING_ID) REFERENCES TOEWIJZING (TOEWIJZING_ID);
-- -- GELEVERDE_ZORG (0..* to 0..1, Connector_ID: 1048)

-- ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_PRESTATIE_VOOR FOREIGN KEY (PRESTATIE_VOOR_CLIENT_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- PRESTATIE_VOOR (0..* to 0..1, Connector_ID: 1049)

-- ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_IS_OP_BASIS_VAN FOREIGN KEY (IS_OP_BASIS_VAN_DECLARATIEREGEL_ID) REFERENCES DECLARATIEREGEL (DECLARATIEREGEL_ID);
-- -- IS_OP_BASIS_VAN (1 to 0..*, Connector_ID: 1052)

-- ALTER TABLE DECLARATIEREGEL ADD CONSTRAINT FK_DECLARATIEREGEL_BETREFT FOREIGN KEY (BETREFT_CLIENT_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- BETREFT (0..* to 1, Connector_ID: 1053)

-- ALTER TABLE DECLARATIEREGEL ADD CONSTRAINT FK_DECLARATIEREGEL_VALT_BINNEN FOREIGN KEY (VALT_BINNEN_DECLARATIE_ID) REFERENCES DECLARATIE (DECLARATIE_ID);
-- -- VALT_BINNEN (0..* to 1, Connector_ID: 1054)

-- ALTER TABLE DECLARATIE ADD CONSTRAINT FK_DECLARATIE_INGEDIEND_DOOR FOREIGN KEY (INGEDIEND_DOOR_LEVERANCIER_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- INGEDIEND_DOOR (0..* to 1, Connector_ID: 1055)

-- ALTER TABLE PGB_TOEKENNING ADD CONSTRAINT FK_PGB_TOEKENNING_BETREFT FOREIGN KEY (BETREFT_BUDGETUITPUTTING_ID) REFERENCES BUDGETUITPUTTING (BUDGETUITPUTTING_ID);
-- -- BETREFT (1 to 0..*, Connector_ID: 1056)

-- ALTER TABLE PGB_TOEKENNING ADD CONSTRAINT FK_PGB_TOEKENNING_BETREFT_2 FOREIGN KEY (BETREFT_BESCHIKTE_VOORZIENING_ID) REFERENCES BESCHIKTE_VOORZIENING (BESCHIKTE_VOORZIENING_ID);
-- -- BETREFT (0..* to 1, Connector_ID: 1058)

-- ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_HEEFT FOREIGN KEY (HEEFT_LEVERINGSVORM_293_ID) REFERENCES LEVERINGSVORM_293 (LEVERINGSVORM_293_ID);
-- -- HEEFT (0..* to 1, Connector_ID: 1059)

-- ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_TOEGEWEZEN_PRODUCT FOREIGN KEY (TOEGEWEZEN_PRODUCT_TOEWIJZING_ID) REFERENCES TOEWIJZING (TOEWIJZING_ID);
-- -- TOEGEWEZEN_PRODUCT (1..* to 0..1, Connector_ID: 1060)

-- ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_IS_VOORZIENING FOREIGN KEY (IS_VOORZIENING_VOORZIENING_ID) REFERENCES VOORZIENING (VOORZIENING_ID);
-- -- IS_VOORZIENING (0..* to 1, Connector_ID: 1061)

-- ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_LEIDT_TOT FOREIGN KEY (LEIDT_TOT_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- -- LEIDT_TOT (0..* to 0..1, Connector_ID: 1062)

-- ALTER TABLE DECLARATIEREGEL ADD CONSTRAINT FK_DECLARATIEREGEL_IS_VOOR FOREIGN KEY (IS_VOOR_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- -- IS_VOOR (0..* to 1, Connector_ID: 1063)

-- ALTER TABLE CLIENTBEGELEIDER ADD CONSTRAINT FK_CLIENTBEGELEIDER_GEEFT_AF FOREIGN KEY (GEEFT_AF_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- -- GEEFT_AF (1 to 0..*, Connector_ID: 1064)

-- ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_GELEVERDE_PRESTATIE FOREIGN KEY (GELEVERDE_PRESTATIE_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- -- GELEVERDE_PRESTATIE (0..* to 0..1, Connector_ID: 1065)

-- ALTER TABLE MELDING_EIGEN_BIJDRAGE ADD CONSTRAINT FK_MELDING_EIGEN_BIJDRAGE_BETREFT FOREIGN KEY (BETREFT_BESCHIKKING_ID) REFERENCES BESCHIKKING (BESCHIKKING_ID);
-- -- BETREFT (0..* to 1, Connector_ID: 1066)

-- ALTER TABLE BESCHIKKING ADD CONSTRAINT FK_BESCHIKKING_TOEWIJZING FOREIGN KEY (TOEWIJZING_TOEWIJZING_ID) REFERENCES TOEWIJZING (TOEWIJZING_ID);
-- -- TOEWIJZING (1 to 0..*, Connector_ID: 1067)

-- ALTER TABLE BESCHIKKING ADD CONSTRAINT FK_BESCHIKKING_HEEFT_VOORZIENINGEN FOREIGN KEY (HEEFT_VOORZIENINGEN_BESCHIKTE_VOORZIENING_ID) REFERENCES BESCHIKTE_VOORZIENING (BESCHIKTE_VOORZIENING_ID);
-- -- HEEFT_VOORZIENINGEN (1 to 1..*, Connector_ID: 1068)

-- ALTER TABLE BESCHIKKING ADD CONSTRAINT FK_BESCHIKKING_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- unnamed (0..* to 1, Connector_ID: 1069)

-- ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_1 FOREIGN KEY (OUDER_1_INGESCHREVENPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- OUDER_1 (1 to 1, Connector_ID: 1871)

-- ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_OUDER_2 FOREIGN KEY (OUDER_2_INGESCHREVENPERSOON_ID) REFERENCES RECHTSPERSOON (RECHTSPERSOON_ID);
-- -- OUDER_2 (1 to 1, Connector_ID: 1873)

-- ALTER TABLE BESCHIKKING ADD CONSTRAINT FK_BESCHIKKING_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- -- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- -- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- -- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_LEVERINGSVORM_287_ENUM_ID FOREIGN KEY (LEVERINGSVORM_287_ENUM_ID) REFERENCES LEVERINGSVORM_309_ENUM (LEVERINGSVORM_309_ENUM_ID);
-- -- LEVERINGSVORM_287_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE BESCHIKTE_VOORZIENING ADD CONSTRAINT FK_BESCHIKTE_VOORZIENING_FREQUENTIE_ENUM_ID FOREIGN KEY (FREQUENTIE_ENUM_ID) REFERENCES FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID);
-- -- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- -- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE LEVERING ADD CONSTRAINT FK_LEVERING_FREQUENTIE_ENUM_ID FOREIGN KEY (FREQUENTIE_ENUM_ID) REFERENCES FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID);
-- -- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE LEVERINGSVORM_293 ADD CONSTRAINT FK_LEVERINGSVORM_293_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- -- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE TARIEF ADD CONSTRAINT FK_TARIEF_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- -- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE TARIEF ADD CONSTRAINT FK_TARIEF_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- -- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- -- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- -- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE TOEWIJZING ADD CONSTRAINT FK_TOEWIJZING_FREQUENTIE_ENUM_ID FOREIGN KEY (FREQUENTIE_ENUM_ID) REFERENCES FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID);
-- -- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_RAAMCONTRACT_ENUM_ID FOREIGN KEY (RAAMCONTRACT_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- -- RAAMCONTRACT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_EENHEID_ENUM_ID FOREIGN KEY (EENHEID_ENUM_ID) REFERENCES EENHEID_ENUM (EENHEID_ENUM_ID);
-- -- EENHEID_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_FREQUENTIE_ENUM_ID FOREIGN KEY (FREQUENTIE_ENUM_ID) REFERENCES FREQUENTIE_ENUM (FREQUENTIE_ENUM_ID);
-- -- FREQUENTIE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE VERZOEK_OM_TOEWIJZING ADD CONSTRAINT FK_VERZOEK_OM_TOEWIJZING_SOORTVERWIJZER_ENUM_ID FOREIGN KEY (SOORTVERWIJZER_ENUM_ID) REFERENCES SOORT_VERWIJZER_ENUM (SOORT_VERWIJZER_ENUM_ID);
-- -- SOORTVERWIJZER_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE VOORZIENING ADD CONSTRAINT FK_VOORZIENING_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- -- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE VOORZIENINGSOORT ADD CONSTRAINT FK_VOORZIENINGSOORT_WET_ENUM_ID FOREIGN KEY (WET_ENUM_ID) REFERENCES WET_ENUM (WET_ENUM_ID);
-- -- WET_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE CLIENT ADD CONSTRAINT FK_CLIENT_GEZAGSDRAGERGEKEND_ENUM_ID FOREIGN KEY (GEZAGSDRAGERGEKEND_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- -- GEZAGSDRAGERGEKEND_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE MEDEWERKER ADD CONSTRAINT FK_MEDEWERKER_EXTERN_ENUM_ID FOREIGN KEY (EXTERN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- -- EXTERN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID FOREIGN KEY (INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- -- INDICATIEAFSCHERMINGPERSOONSGEGEVENS_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE NATUURLIJKPERSOON ADD CONSTRAINT FK_NATUURLIJKPERSOON_INDICATIEOVERLEDEN_ENUM_ID FOREIGN KEY (INDICATIEOVERLEDEN_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- -- INDICATIEOVERLEDEN_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_SIGNALERINGREISDOCUMENT_ENUM_ID FOREIGN KEY (SIGNALERINGREISDOCUMENT_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- -- SIGNALERINGREISDOCUMENT_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_INGEZETENE_ENUM_ID FOREIGN KEY (INGEZETENE_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- -- INGEZETENE_ENUM_ID (1 to 1, Connector_ID: enum_ref)

-- ALTER TABLE INGESCHREVENPERSOON ADD CONSTRAINT FK_INGESCHREVENPERSOON_INDICATIEGEHEIM_ENUM_ID FOREIGN KEY (INDICATIEGEHEIM_ENUM_ID) REFERENCES BOOLEAN_ENUM (BOOLEAN_ENUM_ID);
-- -- INDICATIEGEHEIM_ENUM_ID (1 to 1, Connector_ID: enum_ref)
